from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index$', views.index, name='index'),
    url(r'^ceshi$', views.ceshi, name='ceshi'),
    url(r'^$', views.login_user, name='login'),
    url(r'^logout_user', views.logout_user, name='logout_user'),
    url(r'^reg_user', views.reg_user, name='reg_user'),
    url(r'^welcome', views.welcome),
    url(r'^first_welcome', views.welcome_first, name='first_welcome'),
    url(r'^order$', views.order, name='order'),
    url(r'^order_add$', views.order_add, name='order_add'),
    url(r'^spider$', views.spider, name='spider'),
    url(r'^spider_add/(?P<project_name>.*?)$', views.spider_add, name='spider_add'),
    url(r'^spider_info/(?P<project_name>.*?)/(?P<spider_id>[0-9]+)/(?P<spider_name>.*?)$', views.spider_info, name='spider_info'),
    url(r'^spider_info_data/(?P<spider_name>.*?)$', views.spider_info_data, name='spider_info_data'),
    url(r'^spider_setting/(?P<spider_name>.*?)$', views.spider_setting, name='spider_setting'),
    url(r'^del_param/(?P<spider_name>.*?)/(?P<varname>.*?)$', views.del_param, name='del_param'),
    url(r'^add_param_html/(?P<project_name>.*?)/(?P<spider_name>.*?)$', views.add_param_html, name='add_param_html'),
    url(r'^del_start/(?P<spider_name>.*?)/(?P<spider_id>[0-9]+)$', views.del_start, name='del_start'),
    url(r'^add_param$', views.add_param, name='add_param'),
    url(r'^add_config_html/(?P<project_name>.*?)/(?P<spider_name>.*?)$', views.add_config_html, name='add_config_html'),
    url(r'^add_filed_html/(?P<project_name>.*?)/(?P<spider_name>.*?)$', views.add_filed_html, name='add_filed_html'),
    url(r'^del_pageset/(?P<spider_name>.*?)/(?P<spider_id>[0-9]+)$', views.del_pageset, name='del_pageset'),
    url(r'^del_listsset/(?P<spider_name>.*?)/(?P<spider_id>[0-9]+)$', views.del_listsset, name='del_listsset'),
    url(r'^del_filedset/(?P<spider_name>.*?)/(?P<spider_id>[0-9]+)$', views.del_filedset, name='del_filedset'),
    url(r'^add_config$', views.add_config, name='add_config'),
    url(r'^start_json/(?P<spider_name>.*?)$', views.start_json, name='start_json'),
    url(r'^add_pagepath_html/(?P<project_name>.*?)/(?P<spider_name>.*?)$', views.add_pagepath_html, name='add_pagepath_html'),
    url(r'^add_lists_html/(?P<project_name>.*?)/(?P<spider_name>.*?)$', views.add_lists_html, name='add_lists_html'),
    url(r'^add_pagepath$', views.add_pagepath, name='add_pagepath'),
    url(r'^add_listspath$', views.add_listspath, name='add_listspath'),
    url(r'^add_filedpath$', views.add_filedpath, name='add_filedpath'),
    url(r'^down_add$', views.down_add, name='down_add'),
    url(r'^page_data/(?P<spider_name>.*?)$', views.page_data, name='page_data'),
    url(r'^filed_data/(?P<spider_name>.*?)$', views.filed_data, name='filed_data'),
    url(r'^lists_data/(?P<spider_name>.*?)$', views.lists_data, name='lists_data'),
    url(r'^edit_param/(?P<project_name>.*?)/(?P<spider_name>.*?)/(?P<param_id>[0-9]+)/(?P<varname>.*?)/(?P<vartype>.*?)/(?P<varvalue>.*?)$', views.edit_param, name='edit_param'),
    url(r'^edit_config$', views.edit_config, name='edit_config'),
    #url(r'^edit_config/(?P<project_name>.*?)/(?P<spider_name>.*?)/(?P<spider_id>[0-9]+)/(?P<startrequest>.*?)/(?P<headers>.*?)/(?P<requesttype>.*?)/(?P<formdata>.*?)$', views.edit_config, name='edit_config'),
    url(r'^edit_spider/(?P<spider_id>[0-9]+)/(?P<project_name>.*?)$', views.edit_spider, name='edit_spider'),
    url(r'^spider_refix/(?P<spider_refix_id>[0-9]+)$', views.spider_refix, name='spider_refix'),
    url(r'^spider_del$', views.spider_del, name='spider_del'),
    url(r'^spider_del_info/(?P<spider_id>.*)$', views.spider_del_info, name='spider_del_info'),
    url(r'^spider_del_one/(?P<spider_id>.*)$', views.spider_del_one, name='spider_del_one'),
    url(r'^order_del/(?P<project_id>.*)$', views.order_del, name='order_del'),
    url(r'^spider_lists/(?P<project_id>[0-9]+)/(?P<project_name>.*?)$', views.spider_lists, name='spider_lists'),
    url(r'^first_order/(?P<project_id>.*)$', views.first_order, name='first_order'),
    url(r'^first_order_view/(?P<spider_id>[0-9]+)/(?P<project_name>.*?)$', views.first_order_view, name='first_order_view'),
    url(r'^cate', views.cate),
    url(r'^member', views.member, name='member'),
    url(r'^del_data/(?P<spider_id>[0-9]+)$', views.del_data, name='del_data'),
    url(r'^status_edit/(.*?)$', views.edit_status, name='status_edit'),
    url(r'^edit/(?P<spider_id>[0-9]+)$', views.edit, name='edit'),
    url(r'^edit_action/', views.edit_action, name='edit_action'),
    url(r'^active_member', views.member_first, name='active_member'),
    url(r'^json_data', views.json_data, name='json_data'),
    url(r'^spiders_json/(?P<project_id>[0-9]+)$', views.spiders_json, name='ceshi_json'),
    url(r'^editimport/(?P<spider_id>[0-9]+)$', views.order_view, name='editimport'),
    url(r'^del_order_view/(?P<spider_id>[0-9]+)$', views.del_order_view, name='del_order_view'),
    url(r'^edit_order_view$', views.edit_order_view, name='edit_order_view'),
    url(r'^show_result$', views.show_result, name='show_result'),
    url(r'^table_data$', views.table_data, name='table_data'),
    url(r'^runner/(?P<project_name>.*?)/(?P<spider_name>.*?)$', views.runner, name='runner'),
]