# Generated by Django 2.1.1 on 2019-08-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, null=True)),
                ('dimensions', models.CharField(max_length=255, null=True)),
                ('time_date', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='important_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('dimensions', models.CharField(max_length=255, null=True)),
                ('yesterday_num', models.CharField(max_length=255, null=True)),
                ('today_num', models.CharField(max_length=255, null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='month_datacount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, null=True)),
                ('dimensions', models.CharField(max_length=255, null=True)),
                ('time_date', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('table_dimensions', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='spider_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=255, null=True)),
                ('interval_time', models.CharField(max_length=255, null=True)),
                ('data_base', models.CharField(max_length=255, null=True)),
                ('start_time', models.CharField(max_length=255, null=True)),
                ('end_time', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
                ('server', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
