# Generated by Django 2.1.1 on 2019-08-07 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app_num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=255, null=True)),
                ('appname', models.CharField(max_length=255, null=True)),
                ('applogo', models.CharField(max_length=255, null=True)),
                ('fclassname', models.CharField(max_length=255, null=True)),
                ('kclassname', models.CharField(max_length=255, null=True)),
                ('usenum', models.CharField(max_length=255, null=True)),
                ('growth', models.CharField(max_length=255, null=True)),
                ('daymachinenum', models.CharField(max_length=255, null=True)),
                ('dmgrowth', models.CharField(max_length=255, null=True)),
                ('usetime', models.CharField(max_length=255, null=True)),
                ('timegrowth', models.CharField(max_length=255, null=True)),
                ('timename', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('dimensions', models.CharField(default=0, max_length=255)),
                ('time_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='spider_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=255, null=True)),
                ('interval_time', models.CharField(max_length=255, null=True)),
                ('data_base', models.CharField(max_length=255, null=True)),
                ('start_time', models.CharField(max_length=255, null=True)),
                ('end_time', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
                ('server', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
