# Generated by Django 2.2.7 on 2020-04-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spidername', models.CharField(max_length=255, null=True)),
                ('fieldname', models.CharField(max_length=255, null=True)),
                ('rule', models.CharField(max_length=255, null=True)),
                ('is_many', models.CharField(max_length=255, null=True)),
                ('notename', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='creat_project_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, null=True)),
                ('contrller', models.CharField(max_length=255, null=True)),
                ('spider_count', models.CharField(max_length=255, null=True)),
                ('project_desc', models.CharField(max_length=255, null=True)),
                ('created_time', models.CharField(max_length=255, null=True)),
                ('owner', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='creat_spider_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectname', models.CharField(max_length=255, null=True)),
                ('spidername', models.CharField(max_length=255, null=True)),
                ('islong', models.CharField(max_length=255, null=True)),
                ('spiderdesc', models.CharField(max_length=255, null=True)),
                ('creattime', models.CharField(max_length=255, null=True)),
                ('lasttime', models.CharField(max_length=255, null=True)),
                ('laststatus', models.CharField(max_length=255, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('node', models.CharField(max_length=255, null=True)),
                ('param', models.CharField(max_length=255, null=True)),
                ('count', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='data_count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, null=True)),
                ('dimensions', models.CharField(max_length=255, null=True)),
                ('time_date', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='important_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('dimensions', models.CharField(max_length=255, null=True)),
                ('yesterday_num', models.CharField(max_length=255, null=True)),
                ('today_num', models.CharField(max_length=255, null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='lists_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spidername', models.CharField(max_length=255, null=True)),
                ('listsxpath', models.CharField(max_length=255, null=True)),
                ('contentxpath', models.CharField(max_length=255, null=True)),
                ('callname', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='month_datacount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, null=True)),
                ('dimensions', models.CharField(max_length=255, null=True)),
                ('time_date', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='page_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spidername', models.CharField(max_length=255, null=True)),
                ('pageurl', models.CharField(max_length=255, null=True)),
                ('pagecount', models.CharField(max_length=255, null=True)),
                ('pagevar', models.CharField(max_length=255, null=True)),
                ('callname', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('table_dimensions', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='spider_lists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=255, null=True)),
                ('interval_time', models.CharField(max_length=255, null=True)),
                ('data_base', models.CharField(max_length=255, null=True)),
                ('start_time', models.CharField(max_length=255, null=True)),
                ('end_time', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
                ('server', models.CharField(max_length=255, null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='spider_prarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spidername', models.CharField(max_length=255, null=True)),
                ('varname', models.CharField(max_length=255, null=True)),
                ('vartype', models.CharField(max_length=255, null=True)),
                ('varvalue', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='spider_start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spidername', models.CharField(max_length=255, null=True)),
                ('startrequest', models.CharField(max_length=255, null=True)),
                ('headers', models.TextField(blank=True)),
                ('requesttype', models.CharField(max_length=255, null=True)),
                ('formdata', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
    ]
