# Generated by Django 2.1.1 on 2019-08-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0002_auto_20190807_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_count',
            name='time_date',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
