# Generated by Django 2.1.1 on 2019-08-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0003_auto_20190807_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_count',
            name='time_date',
            field=models.CharField(max_length=30),
        ),
    ]
