# Generated by Django 2.1.1 on 2019-08-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0004_auto_20190807_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_count',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data_count',
            name='dimensions',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='data_count',
            name='time_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
