# Generated by Django 2.1.1 on 2019-08-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0005_auto_20190807_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='month_datacount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, null=True)),
                ('dimensions', models.CharField(max_length=255, null=True)),
                ('time_date', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
