# Generated by Django 2.1.1 on 2019-08-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moniter', '0006_month_datacount'),
    ]

    operations = [
        migrations.CreateModel(
            name='important_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('dimensions', models.CharField(max_length=255, null=True)),
                ('yesterday_num', models.CharField(max_length=255, null=True)),
                ('today_num', models.CharField(max_length=255, null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
